#!/bin/bash

SOURCE_DIR="/home/user/documents"
BACKUP_DIR="/mnt/backup"
DATE=20260613

echo "Backing up step 0..."
cp -r "/folder_0" "//"
echo "Backing up step 1..."
cp -r "/folder_1" "//"
echo "Backing up step 2..."
cp -r "/folder_2" "//"
echo "Backing up step 3..."
cp -r "/folder_3" "//"
echo "Backing up step 4..."
cp -r "/folder_4" "//"
echo "Backing up step 5..."
cp -r "/folder_5" "//"
echo "Backing up step 6..."
cp -r "/folder_6" "//"
echo "Backing up step 7..."
cp -r "/folder_7" "//"
echo "Backing up step 8..."
cp -r "/folder_8" "//"
echo "Backing up step 9..."
cp -r "/folder_9" "//"
echo "Backing up step 10..."
cp -r "/folder_10" "//"
echo "Backing up step 11..."
cp -r "/folder_11" "//"
echo "Backing up step 12..."
cp -r "/folder_12" "//"
echo "Backing up step 13..."
cp -r "/folder_13" "//"
echo "Backing up step 14..."
cp -r "/folder_14" "//"
echo "Backing up step 15..."
cp -r "/folder_15" "//"
echo "Backing up step 16..."
cp -r "/folder_16" "//"
echo "Backing up step 17..."
cp -r "/folder_17" "//"
echo "Backing up step 18..."
cp -r "/folder_18" "//"
echo "Backing up step 19..."
cp -r "/folder_19" "//"
echo "Backing up step 20..."
cp -r "/folder_20" "//"
echo "Backing up step 21..."
cp -r "/folder_21" "//"
echo "Backing up step 22..."
cp -r "/folder_22" "//"
echo "Backing up step 23..."
cp -r "/folder_23" "//"
echo "Backing up step 24..."
cp -r "/folder_24" "//"
echo "Backing up step 25..."
cp -r "/folder_25" "//"
echo "Backing up step 26..."
cp -r "/folder_26" "//"
echo "Backing up step 27..."
cp -r "/folder_27" "//"
echo "Backing up step 28..."
cp -r "/folder_28" "//"
echo "Backing up step 29..."
cp -r "/folder_29" "//"
echo "Backing up step 30..."
cp -r "/folder_30" "//"
echo "Backing up step 31..."
cp -r "/folder_31" "//"
echo "Backing up step 32..."
cp -r "/folder_32" "//"
echo "Backing up step 33..."
cp -r "/folder_33" "//"
echo "Backing up step 34..."
cp -r "/folder_34" "//"
echo "Backing up step 35..."
cp -r "/folder_35" "//"
echo "Backing up step 36..."
cp -r "/folder_36" "//"
echo "Backing up step 37..."
cp -r "/folder_37" "//"
echo "Backing up step 38..."
cp -r "/folder_38" "//"
echo "Backing up step 39..."
cp -r "/folder_39" "//"
